# =============================================================================
#  clean.ps1 — Remove build artifacts produced by setup_build_env.ps1.
# -----------------------------------------------------------------------------
#  This script removes ONLY the artifacts produced by the C extension
#  build. It NEVER touches source code, documentation, tests, or
#  scripts.
#
#  By default it removes:
#
#    ext/lingofuse_ext/Makefile                     (generated by extconf.rb)
#    ext/lingofuse_ext/mkmf.log                     (generated by mkmf)
#    ext/lingofuse_ext/*.o                          (object files)
#    ext/lingofuse_ext/lingofuse_ext.so             (built extension)
#    ext/lingofuse_ext/lingofuse_ext*.def           (export definition)
#    lib/lingofuse_ext.so                           (installed copy)
#
#  It ALWAYS preserves:
#
#    ext/lingofuse_ext/extconf.rb                   (source)
#    ext/lingofuse_ext/lingofuse_ext.c              (source)
#    lib/lingofuse.rb                               (source)
#    lib/lingofuse/*.rb                             (source)
#    test/*.rb                                      (source)
#    cross/*.rb                                     (source)
#    *.md, *.ps1, *.sh, Gemfile, gemspec, Rakefile  (project files)
#
#  Usage:
#
#      cd D:\CoreLibrary\LingoFuse\ruby
#      powershell -ExecutionPolicy Bypass -File clean.ps1
#
#  Options:
#
#      -DryRun            List what would be removed, but do not delete.
#      -KeepInstalled     Do not remove lib/lingofuse_ext.so. Only the
#                         intermediate artifacts inside
#                         ext/lingofuse_ext/ are removed. Useful when
#                         you want to rebuild the extension in place
#                         while keeping the currently installed copy
#                         usable.
#
#  Exit codes:
#
#      0   every targeted file was removed (or did not exist)
#      1   at least one file could not be removed
#
# =============================================================================

[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$KeepInstalled
)

$ErrorActionPreference = 'Continue'

# =============================================================================
# Reporter
# =============================================================================

function Write-Section {
    param([string]$Title)
    Write-Host ''
    Write-Host ('=' * 72)
    Write-Host $Title
    Write-Host ('=' * 72)
}

function Write-Ok   { param([string]$m) Write-Host "  [OK]   $m" }
function Write-Fail { param([string]$m) Write-Host "  [FAIL] $m" }
function Write-Warn { param([string]$m) Write-Host "  [WARN] $m" }
function Write-Info { param([string]$m) Write-Host "         $m" }
function Write-Skip { param([string]$m) Write-Host "  [SKIP] $m" }

# =============================================================================
# Section 0 — Prerequisites
# =============================================================================

Write-Section '0. Prerequisites'

if (-not $PSScriptRoot) {
    Write-Fail '$PSScriptRoot is empty.'
    Write-Info 'Run this script as a file:'
    Write-Info '    powershell -ExecutionPolicy Bypass -File clean.ps1'
    exit 1
}
Write-Ok "Script directory: $PSScriptRoot"

if ($DryRun) {
    Write-Info 'DRY-RUN mode: no file will be deleted.'
}
if ($KeepInstalled) {
    Write-Info 'KEEP-INSTALLED mode: lib/lingofuse_ext.so will be preserved.'
}

# =============================================================================
# Section 1 — Locate artifacts
# =============================================================================

Write-Section '1. Locating build artifacts'

$extDir = Join-Path $PSScriptRoot 'ext\lingofuse_ext'
$libDir = Join-Path $PSScriptRoot 'lib'

# -----------------------------------------------------------------------------
# ext/lingofuse_ext/ intermediate artifacts
#
# Each entry is an exact file name, resolved against $extDir. The list
# is deliberately explicit so that nothing outside this set is ever
# touched by mistake.
# -----------------------------------------------------------------------------

$extArtifactNames = @(
    'Makefile'
    'mkmf.log'
    'lingofuse_ext.o'
    'lingofuse_ext.so'
    'lingofuse_ext.dll'
    'lingofuse_ext-x64-mingw-ucrt.def'
    'lingofuse_ext.def'
)

# Extra patterns for files whose exact names vary by toolchain: any
# *.o and any lingofuse_ext*.def.
$extArtifactPatterns = @(
    '*.o'
    'lingofuse_ext*.def'
    'lingofuse_ext*.so'
    'lingofuse_ext*.dll'
)

$targets = New-Object System.Collections.Generic.List[object]

if (Test-Path $extDir) {
    foreach ($name in $extArtifactNames) {
        $p = Join-Path $extDir $name
        if (Test-Path $p -PathType Leaf) {
            $targets.Add([PSCustomObject]@{
                Path   = $p
                Reason = 'ext artifact'
            }) | Out-Null
        }
    }

    foreach ($pattern in $extArtifactPatterns) {
        # NOTE: the local variable is named $found, not $matches.
        # $matches is a PowerShell automatic variable (the result
        # hashtable of the -match operator) and must not be assigned
        # to.
        $found = @(
            Get-ChildItem -Path $extDir -Filter $pattern -File `
                -ErrorAction SilentlyContinue
        )
        foreach ($m in $found) {
            # Deduplicate against the explicit list above.
            $already = $false
            foreach ($t in $targets) {
                if ($t.Path -eq $m.FullName) { $already = $true; break }
            }
            if (-not $already) {
                $targets.Add([PSCustomObject]@{
                    Path   = $m.FullName
                    Reason = "ext artifact (pattern $pattern)"
                }) | Out-Null
            }
        }
    }
} else {
    Write-Info "ext directory not present: $extDir"
}

# -----------------------------------------------------------------------------
# lib/lingofuse_ext.so — installed copy
#
# This file is a build output, not source. It is created by
# setup_build_env.ps1 when it copies the built extension into lib/.
# -----------------------------------------------------------------------------

if (-not $KeepInstalled) {
    $installedExt = Join-Path $libDir 'lingofuse_ext.so'
    if (Test-Path $installedExt -PathType Leaf) {
        $targets.Add([PSCustomObject]@{
            Path   = $installedExt
            Reason = 'installed extension'
        }) | Out-Null
    }
} else {
    Write-Info 'Skipping lib/lingofuse_ext.so (--KeepInstalled).'
}

if ($targets.Count -eq 0) {
    Write-Ok 'Nothing to clean; the project is already clean.'
    Write-Section 'Done'
    exit 0
}

# =============================================================================
# Section 2 — List targets
# =============================================================================

Write-Section '2. Targets'

$totalBytes = 0
foreach ($t in $targets) {
    try {
        $size = (Get-Item $t.Path).Length
    } catch {
        $size = 0
    }
    $totalBytes += $size
    $rel = $t.Path.Substring($PSScriptRoot.Length).TrimStart('\', '/')
    Write-Info ("{0,10} bytes  {1}" -f $size, $rel)
}

Write-Host ''
Write-Info ("Total: {0} file(s), {1} bytes" -f $targets.Count, $totalBytes)

if ($DryRun) {
    Write-Section 'Done'
    Write-Host '  Dry run complete. Re-run without -DryRun to delete.'
    Write-Host ''
    exit 0
}

# =============================================================================
# Section 3 — Delete
# =============================================================================

Write-Section '3. Deleting'

$removed  = 0
$failed   = 0
$failures = New-Object System.Collections.Generic.List[object]

foreach ($t in $targets) {
    $rel = $t.Path.Substring($PSScriptRoot.Length).TrimStart('\', '/')
    try {
        Remove-Item $t.Path -Force -ErrorAction Stop
        Write-Ok "Removed: $rel"
        $removed++
    } catch {
        Write-Fail "Cannot remove: $rel"
        Write-Info "  reason: $($_.Exception.Message)"
        $failed++
        $failures.Add([PSCustomObject]@{
            Path   = $rel
            Reason = $_.Exception.Message
        }) | Out-Null
    }
}

# =============================================================================
# Section 4 — Report
# =============================================================================

Write-Section 'Report'

Write-Host "  Removed : $removed"
Write-Host "  Failed  : $failed"
Write-Host ''

if ($failed -eq 0) {
    Write-Host '  The project is clean.'
    Write-Host ''
    Write-Host '  To rebuild the C extension, run:'
    Write-Host ''
    Write-Host '      powershell -ExecutionPolicy Bypass -File setup_build_env.ps1'
    Write-Host ''
    exit 0
}

Write-Host '  Some files could not be removed.'
Write-Host ''
Write-Host '  The most common cause is a running Ruby process that has'
Write-Host '  loaded lingofuse_ext.so. Windows does not allow an open file'
Write-Host '  to be deleted.'
Write-Host ''
Write-Host '  Affected files:'
foreach ($f in $failures) {
    Write-Host "    $($f.Path)"
}
Write-Host ''
Write-Host '  Close any Ruby process that may have loaded it:'
Write-Host '    * running tests (test/test_*.rb)'
Write-Host '    * irb / pry shells'
Write-Host '    * VS Code rdbg debug sessions'
Write-Host '    * any background service that required lingofuse_ext'
Write-Host ''
Write-Host '  To list running Ruby processes:'
Write-Host '      Get-Process ruby -ErrorAction SilentlyContinue'
Write-Host ''
Write-Host '  Then re-run this script.'
Write-Host ''
exit 1