// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Regenerate with: dart run ffigen

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated FFI bindings for LingoFuse.h
class LingoFuseBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LingoFuseBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LingoFuseBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Loads the LingoFuse dynamic library and resolves all exported symbols.
  ///
  /// Resolution order:
  /// 1. The directory containing the current executable.
  /// 2. The system search path.
  ///
  /// @return 1 on success, 0 on failure.
  /// @note Must be called before any other LF_* function.
  int LF_LoadLibrary() {
    return _LF_LoadLibrary();
  }

  late final _LF_LoadLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('LF_LoadLibrary');
  late final _LF_LoadLibrary = _LF_LoadLibraryPtr.asFunction<int Function()>();

  /// @brief Unloads the dynamic library and clears all cached function pointers.
  ///
  /// Safe to call multiple times.
  void LF_FreeLibrary() {
    return _LF_FreeLibrary();
  }

  late final _LF_FreeLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('LF_FreeLibrary');
  late final _LF_FreeLibrary = _LF_FreeLibraryPtr.asFunction<void Function()>();

  /// @brief Creates a new auto-recycled data handle bound to the given API name.
  ///
  /// The initial payload is empty. The handle must be freed with LF_FreeData().
  ///
  /// Auto-recycle behaviour:
  /// - The handle is added to the library's idle pool.
  /// - The pool scans every 5 seconds and frees any handle that has been
  /// idle for more than 10 minutes.
  /// - Any accessor call (LF_GetSize, LF_GetPos, LF_ReadBuffer,
  /// LF_WriteBuffer, ...) refreshes the idle timestamp.
  /// - LF_FreeData() marks the handle for release; the actual release
  /// happens on the next pool scan (at most 5 seconds later).
  ///
  /// @param method_name  UTF-8, null-terminated API name.
  /// @return A new TDataHnd (never NULL on success).
  TDataHnd LF_CreateData(
    ffi.Pointer<ffi.Char> method_name,
  ) {
    return _LF_CreateData(
      method_name,
    );
  }

  late final _LF_CreateDataPtr =
      _lookup<ffi.NativeFunction<TDataHnd Function(ffi.Pointer<ffi.Char>)>>(
          'LF_CreateData');
  late final _LF_CreateData =
      _LF_CreateDataPtr.asFunction<TDataHnd Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Creates a new PERMANENT data handle bound to the given API name.
  ///
  /// Difference from LF_CreateData:
  /// - The handle is NOT added to the library's idle pool.
  /// - The automatic idle-timeout reclaimer will NEVER free it, no matter
  /// how long it has been idle.
  /// - LF_FreeData() releases it IMMEDIATELY (synchronously), rather than
  /// merely marking it as deleted for a later pool scan.
  ///
  /// When to use:
  /// - Handles that must survive for the entire lifetime of the process,
  /// or for an unbounded period (cached request templates, long-lived
  /// scratch buffers, global registries, etc.).
  ///
  /// When NOT to use:
  /// - Short-lived or one-shot handles. For those, use LF_CreateData so
  /// the pool can reclaim any handle you forget to free.
  ///
  /// [PITFALL - LIFETIME]
  /// "Permanent" means "not automatically reclaimed", NOT "never released".
  /// You are fully responsible for calling LF_FreeData. There is no pool
  /// safety net: losing the pointer leaks the handle for the lifetime of
  /// the process.
  ///
  /// [PITFALL - SYNCHRONOUS FREE]
  /// When LF_FreeData is called on a permanent handle, the release happens
  /// inside that call. Do not touch the handle after LF_FreeData returns.
  ///
  /// [PITFALL - NO-OP WINDOW]
  /// LF_FreeData is a no-op while the simulated main thread is not active
  /// (i.e. before LF_PrepareDone or after LF_ExitMainThread). Permanent
  /// handles created in that window stay allocated until the process
  /// terminates.
  ///
  /// [PITFALL - TIMESTAMPS IRRELEVANT]
  /// Every accessor still updates the handle's internal updated flag, but
  /// the pool scanner never reads it for permanent handles (the handle is
  /// not in the pool at all).
  ///
  /// @param method_name  UTF-8, null-terminated API name.
  /// @return A new TDataHnd (never NULL on success). Must be freed with
  /// LF_FreeData().
  TDataHnd LF_CreateData_Permanent(
    ffi.Pointer<ffi.Char> method_name,
  ) {
    return _LF_CreateData_Permanent(
      method_name,
    );
  }

  late final _LF_CreateData_PermanentPtr =
      _lookup<ffi.NativeFunction<TDataHnd Function(ffi.Pointer<ffi.Char>)>>(
          'LF_CreateData_Permanent');
  late final _LF_CreateData_Permanent = _LF_CreateData_PermanentPtr.asFunction<
      TDataHnd Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Destroys a data handle and releases its memory.
  ///
  /// @param hnd  Handle to free. NULL is accepted and ignored.
  ///
  /// [PITFALL] If the simulated main thread is not active (before
  /// LF_PrepareDone or after LF_ExitMainThread), this call is a NO-OP.
  /// It is intentionally so, to avoid double-free during library
  /// initialisation/finalisation.
  ///
  /// [PITFALL] For auto-recycled handles (created with LF_CreateData),
  /// this only sets the "deleted" flag; the actual release happens on
  /// the next pool scan (at most 5 seconds later). For permanent handles,
  /// the release is synchronous.
  void LF_FreeData(
    TDataHnd hnd,
  ) {
    return _LF_FreeData(
      hnd,
    );
  }

  late final _LF_FreeDataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(TDataHnd)>>('LF_FreeData');
  late final _LF_FreeData =
      _LF_FreeDataPtr.asFunction<void Function(TDataHnd)>();

  /// @brief Returns a pointer to the internal buffer.
  ///
  /// The pointer is valid until the handle is freed or resized. Do NOT free it.
  ///
  /// @param hnd  Data handle.
  /// @return Pointer to internal memory, or NULL if the handle is empty.
  ffi.Pointer<ffi.Void> LF_GetBuffer(
    TDataHnd hnd,
  ) {
    return _LF_GetBuffer(
      hnd,
    );
  }

  late final _LF_GetBufferPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(TDataHnd)>>(
          'LF_GetBuffer');
  late final _LF_GetBuffer =
      _LF_GetBufferPtr.asFunction<ffi.Pointer<ffi.Void> Function(TDataHnd)>();

  /// @brief Writes @p size bytes at the current position; advances the position.
  ///
  /// @param hnd   Data handle.
  /// @param buff  Source buffer.
  /// @param size  Number of bytes to write.
  /// @return Number of bytes actually written (normally equals @p size).
  int LF_WriteBuffer(
    TDataHnd hnd,
    ffi.Pointer<ffi.Void> buff,
    int size,
  ) {
    return _LF_WriteBuffer(
      hnd,
      buff,
      size,
    );
  }

  late final _LF_WriteBufferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              TDataHnd, ffi.Pointer<ffi.Void>, ffi.Int64)>>('LF_WriteBuffer');
  late final _LF_WriteBuffer = _LF_WriteBufferPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Void>, int)>();

  /// @brief Reads up to @p size bytes from the current position into @p buff.
  ///
  /// @param hnd   Data handle.
  /// @param buff  Destination buffer.
  /// @param size  Maximum number of bytes to read.
  /// @return Number of bytes actually read.
  int LF_ReadBuffer(
    TDataHnd hnd,
    ffi.Pointer<ffi.Void> buff,
    int size,
  ) {
    return _LF_ReadBuffer(
      hnd,
      buff,
      size,
    );
  }

  late final _LF_ReadBufferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              TDataHnd, ffi.Pointer<ffi.Void>, ffi.Int64)>>('LF_ReadBuffer');
  late final _LF_ReadBuffer = _LF_ReadBufferPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Void>, int)>();

  /// @brief Returns the current read/write position.
  int LF_GetPos(
    TDataHnd hnd,
  ) {
    return _LF_GetPos(
      hnd,
    );
  }

  late final _LF_GetPosPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(TDataHnd)>>('LF_GetPos');
  late final _LF_GetPos = _LF_GetPosPtr.asFunction<int Function(TDataHnd)>();

  /// @brief Sets the current read/write position.
  ///
  /// If @p pos exceeds the current size, the buffer is implicitly expanded.
  void LF_SetPos(
    TDataHnd hnd,
    int pos,
  ) {
    return _LF_SetPos(
      hnd,
      pos,
    );
  }

  late final _LF_SetPosPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(TDataHnd, ffi.Int64)>>(
          'LF_SetPos');
  late final _LF_SetPos =
      _LF_SetPosPtr.asFunction<void Function(TDataHnd, int)>();

  /// @brief Returns the total buffer size in bytes.
  int LF_GetSize(
    TDataHnd hnd,
  ) {
    return _LF_GetSize(
      hnd,
    );
  }

  late final _LF_GetSizePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(TDataHnd)>>('LF_GetSize');
  late final _LF_GetSize = _LF_GetSizePtr.asFunction<int Function(TDataHnd)>();

  /// @brief Adjusts the buffer size. Newly added space is uninitialized.
  void LF_SetSize(
    TDataHnd hnd,
    int size,
  ) {
    return _LF_SetSize(
      hnd,
      size,
    );
  }

  late final _LF_SetSizePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(TDataHnd, ffi.Int64)>>(
          'LF_SetSize');
  late final _LF_SetSize =
      _LF_SetSizePtr.asFunction<void Function(TDataHnd, int)>();

  /// @brief Creates a new application with the given name and description.
  ///
  /// @param app_name  UTF-8, null-terminated application name (unique on the
  /// wire; matching is case-insensitive).
  /// @param desc      UTF-8, null-terminated description. A NULL value is
  /// treated as an empty string by this wrapper.
  /// @return A new TAppHnd (never NULL on success).
  TAppHnd LF_CreateApp(
    ffi.Pointer<ffi.Char> app_name,
    ffi.Pointer<ffi.Char> desc,
  ) {
    return _LF_CreateApp(
      app_name,
      desc,
    );
  }

  late final _LF_CreateAppPtr = _lookup<
      ffi.NativeFunction<
          TAppHnd Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('LF_CreateApp');
  late final _LF_CreateApp = _LF_CreateAppPtr.asFunction<
      TAppHnd Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Detaches the application from all clients and stops its sequenced
  /// notification threads.
  ///
  /// The underlying application object is NOT destroyed immediately; it remains
  /// in the global pool until LF_Shutdown() is called. After LF_FreeApp() the
  /// handle must be considered invalid.
  ///
  /// @param app_hnd  Application handle.
  void LF_FreeApp(
    TAppHnd app_hnd,
  ) {
    return _LF_FreeApp(
      app_hnd,
    );
  }

  late final _LF_FreeAppPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(TAppHnd)>>('LF_FreeApp');
  late final _LF_FreeApp = _LF_FreeAppPtr.asFunction<void Function(TAppHnd)>();

  /// @brief Generates a globally unique application name.
  ///
  /// The name is built from active C4 tunnel addresses, process name (with PID),
  /// and a high-resolution timestamp.
  ///
  /// IMPORTANT (Pascal LF-APP-003):
  /// Must be called AFTER LF_PrepareDone() has returned 1. Otherwise the
  /// generated name lacks the tunnel information and may not be unique.
  ///
  /// IMPORTANT (Pascal LF-APP-004):
  /// The returned pointer is valid for ONLY 5 SECONDS. The library frees the
  /// underlying memory after that time. Copy the string immediately
  /// (e.g., via strdup, or a stack/heap buffer) before the pointer becomes
  /// invalid.
  ///
  /// @return Pointer to a null-terminated UTF-8 string (do not free).
  /// Returns an empty string "" on failure.
  ffi.Pointer<ffi.Char> LF_Generate_AppName() {
    return _LF_Generate_AppName();
  }

  late final _LF_Generate_AppNamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'LF_Generate_AppName');
  late final _LF_Generate_AppName =
      _LF_Generate_AppNamePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// @brief Retrieves the application name associated with the given handle.
  ///
  /// Same 5-second validity rule as LF_Generate_AppName (Pascal LF-APP-004).
  /// Copy the string immediately.
  ///
  /// @param app_hnd  Application handle.
  /// @return Pointer to a null-terminated UTF-8 string (do not free).
  /// Returns an empty string "" on failure.
  ffi.Pointer<ffi.Char> LF_Get_AppName(
    TAppHnd app_hnd,
  ) {
    return _LF_Get_AppName(
      app_hnd,
    );
  }

  late final _LF_Get_AppNamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(TAppHnd)>>(
          'LF_Get_AppName');
  late final _LF_Get_AppName =
      _LF_Get_AppNamePtr.asFunction<ffi.Pointer<ffi.Char> Function(TAppHnd)>();

  /// @brief Binds the application to all currently unbound LingoFuse clients.
  ///
  /// Must be called AFTER LF_PrepareDone() has returned 1 and while the
  /// simulated main thread is active. A client is eligible for binding only if
  /// it has no app attached yet (Cli.app == NULL). Each client can host at
  /// most one application.
  ///
  /// @param app_hnd  Application handle.
  /// @return Number of clients successfully bound. 0 means either the main
  /// thread is not active or all clients are already occupied.
  int LF_BindApp(
    TAppHnd app_hnd,
  ) {
    return _LF_BindApp(
      app_hnd,
    );
  }

  late final _LF_BindAppPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TAppHnd)>>('LF_BindApp');
  late final _LF_BindApp = _LF_BindAppPtr.asFunction<int Function(TAppHnd)>();

  /// @brief Registers a Call API (request-response).
  ///
  /// @param app_hnd      Application handle.
  /// @param method_name  UTF-8, null-terminated API name (case-insensitive).
  /// @param desc         UTF-8, null-terminated description. A NULL value is
  /// treated as an empty string by this wrapper.
  /// @param trigger      User-supplied pointer passed back to the callback.
  /// @param on_call      Callback function (must use LF_CDECL).
  /// @return 1 on success, 0 on failure (e.g., duplicate API name).
  int LF_RegisterCall(
    TAppHnd app_hnd,
    ffi.Pointer<ffi.Char> method_name,
    ffi.Pointer<ffi.Char> desc,
    ffi.Pointer<ffi.Void> trigger,
    LF_CallFunc on_call,
  ) {
    return _LF_RegisterCall(
      app_hnd,
      method_name,
      desc,
      trigger,
      on_call,
    );
  }

  late final _LF_RegisterCallPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              TAppHnd,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Void>,
              LF_CallFunc)>>('LF_RegisterCall');
  late final _LF_RegisterCall = _LF_RegisterCallPtr.asFunction<
      int Function(TAppHnd, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Void>, LF_CallFunc)>();

  /// @brief Registers a Notify API (one-way).
  ///
  /// @param app_hnd      Application handle.
  /// @param method_name  UTF-8, null-terminated API name (case-insensitive).
  /// @param desc         UTF-8, null-terminated description. A NULL value is
  /// treated as an empty string by this wrapper.
  /// @param trigger      User-supplied pointer passed back to the callback.
  /// @param on_notify    Callback function (must use LF_CDECL).
  /// @return 1 on success, 0 on failure (e.g., duplicate API name).
  int LF_RegisterNotify(
    TAppHnd app_hnd,
    ffi.Pointer<ffi.Char> method_name,
    ffi.Pointer<ffi.Char> desc,
    ffi.Pointer<ffi.Void> trigger,
    LF_NotifyFunc on_notify,
  ) {
    return _LF_RegisterNotify(
      app_hnd,
      method_name,
      desc,
      trigger,
      on_notify,
    );
  }

  late final _LF_RegisterNotifyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              TAppHnd,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Void>,
              LF_NotifyFunc)>>('LF_RegisterNotify');
  late final _LF_RegisterNotify = _LF_RegisterNotifyPtr.asFunction<
      int Function(TAppHnd, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Void>, LF_NotifyFunc)>();

  /// @brief Unregisters a previously registered API by name.
  ///
  /// The removal takes effect locally immediately. A network broadcast is
  /// triggered; remote peers will stop seeing the API within approximately
  /// 3 seconds (Pascal LF-CHK-001).
  ///
  /// @return 1 if the API was found and removed, 0 otherwise.
  int LF_Unregister(
    TAppHnd app_hnd,
    ffi.Pointer<ffi.Char> method_name,
  ) {
    return _LF_Unregister(
      app_hnd,
      method_name,
    );
  }

  late final _LF_UnregisterPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(TAppHnd, ffi.Pointer<ffi.Char>)>>(
      'LF_Unregister');
  late final _LF_Unregister = _LF_UnregisterPtr.asFunction<
      int Function(TAppHnd, ffi.Pointer<ffi.Char>)>();

  /// @brief Executes a Call API locally within the same process.
  ///
  /// @param app_hnd  Application handle.
  /// @param param    Input data handle (not freed by this function).
  /// @return A new result data handle (must be freed by the caller).
  /// Never NULL on success; if the underlying call fails, an empty
  /// handle (size 0) is returned.
  TDataHnd LF_LocalCall(
    TAppHnd app_hnd,
    TDataHnd param,
  ) {
    return _LF_LocalCall(
      app_hnd,
      param,
    );
  }

  late final _LF_LocalCallPtr =
      _lookup<ffi.NativeFunction<TDataHnd Function(TAppHnd, TDataHnd)>>(
          'LF_LocalCall');
  late final _LF_LocalCall =
      _LF_LocalCallPtr.asFunction<TDataHnd Function(TAppHnd, TDataHnd)>();

  /// @brief Executes a Notify API locally within the same process.
  ///
  /// @param app_hnd  Application handle.
  /// @param param    Input data handle (not freed by this function).
  void LF_LocalNotify(
    TAppHnd app_hnd,
    TDataHnd param,
  ) {
    return _LF_LocalNotify(
      app_hnd,
      param,
    );
  }

  late final _LF_LocalNotifyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(TAppHnd, TDataHnd)>>(
          'LF_LocalNotify');
  late final _LF_LocalNotify =
      _LF_LocalNotifyPtr.asFunction<void Function(TAppHnd, TDataHnd)>();

  /// @brief Clears any previously prepared services and clients.
  ///
  /// Call this before preparing a new set to avoid conflicts. Does not affect
  /// already running services/clients; it only clears the preparation queue.
  void LF_ResetPrepare() {
    return _LF_ResetPrepare();
  }

  late final _LF_ResetPreparePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('LF_ResetPrepare');
  late final _LF_ResetPrepare =
      _LF_ResetPreparePtr.asFunction<void Function()>();

  /// @brief Prepares a C4 service listening on @p listening_addr and advertised
  /// as @p physics_addr.
  ///
  /// If the simulated main thread is already running (after LF_PrepareDone),
  /// the service is created and started immediately; otherwise it is queued.
  ///
  /// @return A tag ID, or -1 if the address is a duplicate/invalid.
  int LF_PrepareService(
    ffi.Pointer<ffi.Char> listening_addr,
    ffi.Pointer<ffi.Char> physics_addr,
  ) {
    return _LF_PrepareService(
      listening_addr,
      physics_addr,
    );
  }

  late final _LF_PrepareServicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('LF_PrepareService');
  late final _LF_PrepareService = _LF_PrepareServicePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Prepares a client connecting to @p physics_addr and optionally
  /// attaching @p app_hnd.
  ///
  /// IMPORTANT (Pascal LF-NET-001):
  /// The same physical address can be used for only ONE client. A second
  /// call with the same address returns -1 and logs a "repeat connection"
  /// error, UNLESS the `Overlap_Connection` option is set to True via
  /// LF_SetOption() BEFORE the call.
  ///
  /// Setting `Overlap_Connection=True` allows multiple independent client
  /// tunnels to the same address, each attached to a different app.
  ///
  /// @return A tag ID, or -1 if the address is a duplicate.
  int LF_PrepareClient(
    ffi.Pointer<ffi.Char> physics_addr,
    TAppHnd app_hnd,
  ) {
    return _LF_PrepareClient(
      physics_addr,
      app_hnd,
    );
  }

  late final _LF_PrepareClientPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, TAppHnd)>>(
      'LF_PrepareClient');
  late final _LF_PrepareClient = _LF_PrepareClientPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, TAppHnd)>();

  /// @brief Starts the LingoFuse framework with all prepared services and clients.
  ///
  /// Blocks until the framework is initialised (or until the configured timeout
  /// expires, depending on `Wait_Connection_ReadyOk`).
  ///
  /// IMPORTANT (Pascal LF-NET-003):
  /// LF_PrepareDone() returns 1 ONLY ONCE per process (without an intervening
  /// LF_Shutdown()). A second call returns 0, even though the framework is
  /// already running. Do not interpret 0 on the second call as a failure.
  /// If you must re-initialise, call LF_Shutdown() first.
  ///
  /// @return 1 on success, 0 on failure or repeated call.
  int LF_PrepareDone() {
    return _LF_PrepareDone();
  }

  late final _LF_PrepareDonePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('LF_PrepareDone');
  late final _LF_PrepareDone = _LF_PrepareDonePtr.asFunction<int Function()>();

  /// @brief Signals the simulated main thread to exit gracefully.
  ///
  /// The framework stops processing network events but does not free all
  /// resources. Call LF_Shutdown() for a full cleanup.
  ///
  /// [PITFALL] LF_ExitMainThread also flushes the data handle pool, releasing
  /// every outstanding handle - including those created with
  /// LF_CreateData_Permanent. Do not use any data handle after this call.
  void LF_ExitMainThread() {
    return _LF_ExitMainThread();
  }

  late final _LF_ExitMainThreadPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('LF_ExitMainThread');
  late final _LF_ExitMainThread =
      _LF_ExitMainThreadPtr.asFunction<void Function()>();

  /// @brief Calls a remote API and waits for a response.
  ///
  /// On timeout or failure, an EMPTY data handle (size 0) is returned, NOT a
  /// NULL pointer. Always check LF_GetSize(result) > 0 to detect failures.
  ///
  /// @param app_name    Target application name (UTF-8).
  /// @param param       Input data handle (not freed by this function).
  /// @param timeout_ms  Timeout in milliseconds. 0 means infinite wait.
  /// @return A new result data handle (must be freed by the caller).
  TDataHnd LF_Call(
    ffi.Pointer<ffi.Char> app_name,
    TDataHnd param,
    int timeout_ms,
  ) {
    return _LF_Call(
      app_name,
      param,
      timeout_ms,
    );
  }

  late final _LF_CallPtr = _lookup<
      ffi.NativeFunction<
          TDataHnd Function(
              ffi.Pointer<ffi.Char>, TDataHnd, ffi.Uint64)>>('LF_Call');
  late final _LF_Call = _LF_CallPtr.asFunction<
      TDataHnd Function(ffi.Pointer<ffi.Char>, TDataHnd, int)>();

  /// @brief Sends a one-way notification to a remote application.
  ///
  /// Order of delivery is NOT guaranteed. Use LF_Sequenced_Notify() if
  /// FIFO ordering per (app, api) pair is required.
  ///
  /// @param app_name  Target application name (UTF-8).
  /// @param param     Input data handle (not freed by this function).
  void LF_Notify(
    ffi.Pointer<ffi.Char> app_name,
    TDataHnd param,
  ) {
    return _LF_Notify(
      app_name,
      param,
    );
  }

  late final _LF_NotifyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, TDataHnd)>>('LF_Notify');
  late final _LF_Notify = _LF_NotifyPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, TDataHnd)>();

  /// @brief Sends a one-way notification with FIFO ordering guarantee for the
  /// same (app, api) pair.
  ///
  /// The notification is queued in a dedicated thread per (app, api), so
  /// delivery order is preserved. Large payloads are streamed efficiently.
  /// Returns immediately after queueing.
  ///
  /// @param app_name  Target application name (UTF-8).
  /// @param param     Input data handle (not freed by this function).
  void LF_Sequenced_Notify(
    ffi.Pointer<ffi.Char> app_name,
    TDataHnd param,
  ) {
    return _LF_Sequenced_Notify(
      app_name,
      param,
    );
  }

  late final _LF_Sequenced_NotifyPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>, TDataHnd)>>(
      'LF_Sequenced_Notify');
  late final _LF_Sequenced_Notify = _LF_Sequenced_NotifyPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, TDataHnd)>();

  /// @brief Adjusts a global runtime option.
  ///
  /// Supported option keys (case-insensitive, aliases accepted):
  ///
  /// === Authentication ===
  ///
  /// "password" / "passwd"
  /// C4 P2PVM authentication token (string).
  ///
  /// === Logging & Debugging ===
  ///
  /// "Quiet"
  /// Enable/disable quiet mode (boolean). When enabled, most
  /// internal log messages are suppressed.
  /// "ShowThreadID" / "ShowThread" / "Show_Thread"
  /// Show thread IDs in log output (boolean).
  /// "ConsoleOutput" / "Console_Output"
  /// Enable/disable console logging (boolean).
  ///
  /// === Connection Readiness ===
  ///
  /// "Overlap_Connection" / "Overlap_Client" / "OverlapConnection" /
  /// "OverlapClient" / "OverlapConnect"
  /// Allow multiple client tunnels to the same address (boolean).
  /// When False (default), only one tunnel per address is created;
  /// subsequent LF_PrepareClient calls with a different appHnd are
  /// silently ignored. When True, each LF_PrepareClient call creates
  /// a new independent tunnel bound to the provided appHnd.
  /// "Wait_Connection_ReadyOk" / "Wait_API_Prepare_Done" /
  /// "API_Prepare_Done_Wait" / "WaitConnect" / "Wait_Ready" / "WaitReady"
  /// Block LF_PrepareDone until all prepared clients are connected
  /// and their applications are online (boolean). Default is True.
  /// "Wait_Connection_Timeout" / "Wait_TimeOut" /
  /// "API_Prepare_Done_TimeOut" / "WaitTimeOut"
  /// Timeout for the above wait (integer, milliseconds).
  /// Default is 30000 ms (30 seconds).
  ///
  /// === IPC (Inter-Process Communication) ===
  ///
  /// "IPC_Serv_ThreadCount" / "IPC_ThreadCount" / "IPC_Server_ThreadCount"
  /// Number of IPC server threads (integer).
  /// "IPC_Serv_MaxQueueLength" / "IPC_MaxQueueLength" /
  /// "IPC_Server_MaxQueueLength"
  /// Maximum IPC message queue length (integer).
  /// "IPC_Serv_MaxMsgSize" / "IPC_MaxMsgSize" / "IPC_Server_MaxMsgSize"
  /// Maximum size of a single IPC message in bytes (integer).
  ///
  /// === Sequenced Notifications ===
  ///
  /// "Fixed_Sequenced_Time" / "Fixed_Sequenced_Life"
  /// Idle timeout for sequenced-notification client-selection
  /// fallback (integer, milliseconds). When the candidate with the
  /// oldest timestamp is older than this value, the system falls
  /// back to the newest client to avoid starvation.
  /// Default is 20000 ms (20 seconds).
  ///
  /// === Data Handle Pool ===
  ///
  /// "DataHandle_Idle_Timeout" / "Data_Idle_Timeout" / "Idle_Timeout"
  /// Idle-timeout for automatic reclamation of non-permanent data
  /// handles by the data-handle pool scanner (integer, milliseconds).
  /// >  0 : ENABLED. A tracked handle that has not been accessed
  /// for this long becomes a candidate for release on the
  /// next pool scan. Default is 600000 ms (10 minutes).
  /// <= 0 : DISABLED. Only an explicit LF_FreeData call releases
  /// a handle; the idle-reclaim branch is skipped entirely.
  ///
  /// Notes:
  /// - Any accessor call on the handle (LF_GetSize / LF_GetPos /
  /// LF_ReadBuffer / LF_WriteBuffer / ...) refreshes its idle
  /// timer and postpones the timeout.
  /// - A remote call in flight (internal calling counter > 0)
  /// also postpones the timeout, regardless of idle time.
  /// - This option does NOT affect handles created with
  /// LF_CreateData_Permanent. Those are released synchronously
  /// by LF_FreeData and never enter the idle-reclaim path.
  ///
  /// "DataHandle_Pool_Scan_Interval" / "Data_Scan_Interval" /
  /// "DataHandle_Scan_Interval"
  /// Minimum interval between two consecutive scans of the data-handle
  /// pool by the library's pool scanner (integer, milliseconds).
  /// >  0 : ENABLED. The scanner returns immediately if fewer than
  /// this many milliseconds have elapsed since the last
  /// scan. Default is 5000 ms (5 seconds).
  /// <= 0 : DISABLED. The scanner runs on every progress tick,
  /// without rate-limiting.
  ///
  /// Relationship with DataHandle_Idle_Timeout:
  /// - DataHandle_Pool_Scan_Interval controls HOW OFTEN the pool
  /// is scanned.
  /// - DataHandle_Idle_Timeout controls WHEN a scanned handle is
  /// actually released.
  /// - A handle that becomes eligible at time T is typically
  /// released at T plus up to one scan interval of latency.
  ///
  /// Notes:
  /// - The scanner is driven by the simulated main thread. Its
  /// effective call frequency is bounded below by the main
  /// thread's tick granularity, not by this value alone.
  /// - Setting this very low (< 1 second) is almost never useful:
  /// the pool lock and the O(N) walk dominate the cost, while
  /// the reclamation-latency improvement is negligible.
  /// - Setting this to 0 disables the rate limiter, but does NOT
  /// disable reclamation itself.
  ///
  /// Unknown options are silently ignored. Changes are not persisted across
  /// restarts.
  ///
  /// @param option  UTF-8, null-terminated option name.
  /// @param value   UTF-8, null-terminated value.
  void LF_SetOption(
    ffi.Pointer<ffi.Char> option,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _LF_SetOption(
      option,
      value,
    );
  }

  late final _LF_SetOptionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('LF_SetOption');
  late final _LF_SetOption = _LF_SetOptionPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Returns the number of pending log messages in the status queue.
  ///
  /// The queue holds up to 1000 messages; older messages are discarded when
  /// the limit is reached.
  ///
  /// IMPORTANT (Pascal LF-OPT-001 / LF-OPT-002):
  /// This function relies on the simulated main thread to process the queue.
  /// If the main thread is not running (i.e., before LF_PrepareDone), the
  /// queue may be empty or stale. Use it only after the framework is fully
  /// initialised.
  int LF_GetStatusCount() {
    return _LF_GetStatusCount();
  }

  late final _LF_GetStatusCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('LF_GetStatusCount');
  late final _LF_GetStatusCount =
      _LF_GetStatusCountPtr.asFunction<int Function()>();

  /// @brief Retrieves the next log message from the status queue (FIFO).
  ///
  /// Returns a pointer to an internal static buffer (UTF-8, null-terminated).
  /// The pointer is valid only until the next call to this function; copy the
  /// string immediately if you need to retain it.
  ///
  /// IMPORTANT: Same main-thread dependency as LF_GetStatusCount.
  ///
  /// @return Pointer to the message, or an empty string "" if the queue is
  /// empty. Do NOT free the returned pointer.
  ffi.Pointer<ffi.Char> LF_GetStatus() {
    return _LF_GetStatus();
  }

  late final _LF_GetStatusPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'LF_GetStatus');
  late final _LF_GetStatus =
      _LF_GetStatusPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// @brief Injects a custom log message into the status queue.
  ///
  /// IMPORTANT: Same main-thread dependency as LF_GetStatusCount. Messages
  /// posted before LF_PrepareDone may be discarded.
  ///
  /// @param status  UTF-8, null-terminated message string.
  void LF_PostStatus(
    ffi.Pointer<ffi.Char> status,
  ) {
    return _LF_PostStatus(
      status,
    );
  }

  late final _LF_PostStatusPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'LF_PostStatus');
  late final _LF_PostStatus =
      _LF_PostStatusPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Checks whether the simulated main thread is currently active.
  ///
  /// @return 1 if running, 0 if stopped or not yet started.
  int LF_CheckMainThread() {
    return _LF_CheckMainThread();
  }

  late final _LF_CheckMainThreadPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('LF_CheckMainThread');
  late final _LF_CheckMainThread =
      _LF_CheckMainThreadPtr.asFunction<int Function()>();

  /// @brief Checks whether an application with the given name is available.
  ///
  /// IMPORTANT (Pascal LF-CHK-001):
  /// The lookup is based on a local cache updated via network broadcasts
  /// with a typical propagation delay of about 3 seconds. This function can
  /// return:
  /// - false negatives immediately after an app is registered
  /// - false positives shortly after an app is unregistered
  /// It is a probing tool, not an authoritative existence test. For critical
  /// decisions, call the target API directly and handle timeouts gracefully.
  ///
  /// @param app_name  UTF-8, null-terminated application name.
  /// @return 1 if at least one instance exists, 0 otherwise.
  int LF_CheckApp(
    ffi.Pointer<ffi.Char> app_name,
  ) {
    return _LF_CheckApp(
      app_name,
    );
  }

  late final _LF_CheckAppPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'LF_CheckApp');
  late final _LF_CheckApp =
      _LF_CheckAppPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Checks whether a specific API is available on the network for the
  /// given application.
  ///
  /// Searches both local and remote instances. Same cache-delay caveat as
  /// LF_CheckApp.
  ///
  /// @param app_name  UTF-8, null-terminated application name.
  /// @param api_name  UTF-8, null-terminated API name.
  /// @return 1 if the API is available on at least one instance, 0 otherwise.
  int LF_CheckApi(
    ffi.Pointer<ffi.Char> app_name,
    ffi.Pointer<ffi.Char> api_name,
  ) {
    return _LF_CheckApi(
      app_name,
      api_name,
    );
  }

  late final _LF_CheckApiPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('LF_CheckApi');
  late final _LF_CheckApi = _LF_CheckApiPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Gracefully terminates the entire LingoFuse framework.
  ///
  /// Steps performed (matching Pascal LF_Shutdown):
  /// 1. Clears network event callbacks.
  /// 2. Stops all sequenced notification threads.
  /// 3. Frees all remaining data handles (including any permanent handle
  /// still alive in the global app/queue pools).
  /// 4. Exits the simulated main thread.
  /// 5. Clears the global application pool (destroying all TLF_App objects).
  /// 6. Unloads the IPC library.
  ///
  /// After LF_Shutdown(), the library is fully reset and may be re-initialised
  /// by calling the preparation functions again. Safe to call multiple times.
  ///
  /// Cleanup order (Pascal LF-CLEAN-001):
  /// LF_ExitMainThread -> LF_FreeApp(app) -> LF_Shutdown
  /// Calling LF_Shutdown alone also performs steps 1, 3, and 5 above, so an
  /// explicit LF_FreeApp is not strictly required before shutdown.
  void LF_Shutdown() {
    return _LF_Shutdown();
  }

  late final _LF_ShutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('LF_Shutdown');
  late final _LF_Shutdown = _LF_ShutdownPtr.asFunction<void Function()>();

  /// @brief Installs or clears the global network event handlers.
  ///
  /// Both handlers are process-global; there is no per-client registration.
  ///
  /// "Connect" semantics (Pascal LF-NET-005):
  /// Fires the FIRST time a client receives a service API-info broadcast.
  /// This is NOT the TCP handshake; it is the earliest point at which the
  /// client can actually route remote calls. Gated by the internal
  /// FService_Info_Is_Onlne False -> True transition. Fires at most once
  /// per connection lifecycle (but again after an auto-reconnect).
  ///
  /// "Disconnect" semantics:
  /// Fires once per physical link loss. Automatic reconnects do NOT emit a
  /// Disconnect for the reconnect attempt itself.
  ///
  /// Threading contract (CRITICAL):
  /// - Callbacks run on a BACKGROUND WORKER THREAD, not on the calling
  /// thread and not on the simulated main thread.
  /// - The @c addr argument is valid ONLY during the callback invocation
  /// (the library frees it immediately after the callback returns).
  /// Copy the string inside the callback if you need to retain it
  /// (Pascal LF-NET-006).
  /// - Never call blocking LingoFuse functions inside these callbacks
  /// (LF_Call, LF_LocalCall, LF_PrepareDone, LF_Shutdown). It will deadlock.
  /// - In managed languages (C# / Java / Python ctypes), keep a strong
  /// reference to the delegate/callback object for as long as it is
  /// installed, otherwise the GC may collect it and cause a crash.
  ///
  /// Passing NULL for either argument disables that particular event.
  ///
  /// LF_Shutdown() automatically clears both handlers before teardown.
  ///
  /// @param on_connect     Callback invoked when a client becomes online.
  /// @param on_disconnect  Callback invoked when a client goes offline.
  void LF_Set_Network_Event(
    LF_NetworkEventFunc on_connect,
    LF_NetworkEventFunc on_disconnect,
  ) {
    return _LF_Set_Network_Event(
      on_connect,
      on_disconnect,
    );
  }

  late final _LF_Set_Network_EventPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(LF_NetworkEventFunc,
              LF_NetworkEventFunc)>>('LF_Set_Network_Event');
  late final _LF_Set_Network_Event = _LF_Set_Network_EventPtr.asFunction<
      void Function(LF_NetworkEventFunc, LF_NetworkEventFunc)>();

  /// @brief Returns a pointer to the buffer at the given byte offset.
  ///
  /// Mirrors Pascal's LF_GetBufferOffset. Use this to read a region of the
  /// internal buffer without a copy. The pointer is valid as long as the
  /// handle is not resized or freed.
  ///
  /// @param hnd     Data handle.
  /// @param offset  Byte offset from the start of the buffer (can be 0).
  /// @return Pointer to (buffer + offset), or NULL if the buffer is NULL.
  ffi.Pointer<ffi.Void> LF_GetBufferOffset(
    TDataHnd hnd,
    int offset,
  ) {
    return _LF_GetBufferOffset(
      hnd,
      offset,
    );
  }

  late final _LF_GetBufferOffsetPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<ffi.Void> Function(TDataHnd, ffi.Int64)>>(
      'LF_GetBufferOffset');
  late final _LF_GetBufferOffset = _LF_GetBufferOffsetPtr.asFunction<
      ffi.Pointer<ffi.Void> Function(TDataHnd, int)>();

  /// ----------------------------------------------------------------------------
  /// Atomic write helpers (return 1 on success, 0 on failure)
  /// -------------------------------------------------------------------------
  int LF_WriteInt8(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteInt8(
      hnd,
      value,
    );
  }

  late final _LF_WriteInt8Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Int8)>>(
          'LF_WriteInt8');
  late final _LF_WriteInt8 =
      _LF_WriteInt8Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteUInt8(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteUInt8(
      hnd,
      value,
    );
  }

  late final _LF_WriteUInt8Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Uint8)>>(
          'LF_WriteUInt8');
  late final _LF_WriteUInt8 =
      _LF_WriteUInt8Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteInt16(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteInt16(
      hnd,
      value,
    );
  }

  late final _LF_WriteInt16Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Int16)>>(
          'LF_WriteInt16');
  late final _LF_WriteInt16 =
      _LF_WriteInt16Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteUInt16(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteUInt16(
      hnd,
      value,
    );
  }

  late final _LF_WriteUInt16Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Uint16)>>(
          'LF_WriteUInt16');
  late final _LF_WriteUInt16 =
      _LF_WriteUInt16Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteInt32(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteInt32(
      hnd,
      value,
    );
  }

  late final _LF_WriteInt32Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Int32)>>(
          'LF_WriteInt32');
  late final _LF_WriteInt32 =
      _LF_WriteInt32Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteUInt32(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteUInt32(
      hnd,
      value,
    );
  }

  late final _LF_WriteUInt32Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Uint32)>>(
          'LF_WriteUInt32');
  late final _LF_WriteUInt32 =
      _LF_WriteUInt32Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteInt64(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteInt64(
      hnd,
      value,
    );
  }

  late final _LF_WriteInt64Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Int64)>>(
          'LF_WriteInt64');
  late final _LF_WriteInt64 =
      _LF_WriteInt64Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteUInt64(
    TDataHnd hnd,
    int value,
  ) {
    return _LF_WriteUInt64(
      hnd,
      value,
    );
  }

  late final _LF_WriteUInt64Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Uint64)>>(
          'LF_WriteUInt64');
  late final _LF_WriteUInt64 =
      _LF_WriteUInt64Ptr.asFunction<int Function(TDataHnd, int)>();

  int LF_WriteSingle(
    TDataHnd hnd,
    double value,
  ) {
    return _LF_WriteSingle(
      hnd,
      value,
    );
  }

  late final _LF_WriteSinglePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Float)>>(
          'LF_WriteSingle');
  late final _LF_WriteSingle =
      _LF_WriteSinglePtr.asFunction<int Function(TDataHnd, double)>();

  int LF_WriteDouble(
    TDataHnd hnd,
    double value,
  ) {
    return _LF_WriteDouble(
      hnd,
      value,
    );
  }

  late final _LF_WriteDoublePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(TDataHnd, ffi.Double)>>(
          'LF_WriteDouble');
  late final _LF_WriteDouble =
      _LF_WriteDoublePtr.asFunction<int Function(TDataHnd, double)>();

  /// @brief Writes a UTF-8 string followed by a null terminator (#0).
  ///
  /// Empty strings ("") write exactly one byte: #0.
  ///
  /// A NULL @p value is treated as a failure and returns 0 immediately; no
  /// bytes are written and the cursor is not advanced.
  ///
  /// @param hnd    Data handle.
  /// @param value  Null-terminated UTF-8 string (may be empty, must not be NULL).
  /// @return 1 if the full string plus the null was written, 0 otherwise.
  int LF_WriteString(
    TDataHnd hnd,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _LF_WriteString(
      hnd,
      value,
    );
  }

  late final _LF_WriteStringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Char>)>>('LF_WriteString');
  late final _LF_WriteString = _LF_WriteStringPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Char>)>();

  /// @brief Writes a raw byte sequence followed by a null terminator (#0).
  ///
  /// This is the byte-oriented counterpart of LF_WriteString. Unlike
  /// LF_WriteString, it does NOT stop at embedded #0 bytes; it writes exactly
  /// @p length bytes and appends one additional #0 byte.
  ///
  /// Mirrors Pascal's LF_WriteStringBytes.
  ///
  /// @param hnd     Data handle.
  /// @param data    Source byte buffer (may be NULL only if @p length is 0).
  /// @param length  Number of bytes to write (not including the appended #0).
  /// @return 1 on success, 0 on failure.
  int LF_WriteStringBytes(
    TDataHnd hnd,
    ffi.Pointer<ffi.Void> data,
    int length,
  ) {
    return _LF_WriteStringBytes(
      hnd,
      data,
      length,
    );
  }

  late final _LF_WriteStringBytesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Void>,
              ffi.Int64)>>('LF_WriteStringBytes');
  late final _LF_WriteStringBytes = _LF_WriteStringBytesPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Void>, int)>();

  /// ----------------------------------------------------------------------------
  /// Atomic read helpers (return 1 on success, 0 on failure)
  /// -------------------------------------------------------------------------
  int LF_ReadInt8(
    TDataHnd hnd,
    ffi.Pointer<ffi.Int8> out,
  ) {
    return _LF_ReadInt8(
      hnd,
      out,
    );
  }

  late final _LF_ReadInt8Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Int8>)>>('LF_ReadInt8');
  late final _LF_ReadInt8 = _LF_ReadInt8Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Int8>)>();

  int LF_ReadUInt8(
    TDataHnd hnd,
    ffi.Pointer<ffi.Uint8> out,
  ) {
    return _LF_ReadUInt8(
      hnd,
      out,
    );
  }

  late final _LF_ReadUInt8Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Uint8>)>>('LF_ReadUInt8');
  late final _LF_ReadUInt8 = _LF_ReadUInt8Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Uint8>)>();

  int LF_ReadInt16(
    TDataHnd hnd,
    ffi.Pointer<ffi.Int16> out,
  ) {
    return _LF_ReadInt16(
      hnd,
      out,
    );
  }

  late final _LF_ReadInt16Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Int16>)>>('LF_ReadInt16');
  late final _LF_ReadInt16 = _LF_ReadInt16Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Int16>)>();

  int LF_ReadUInt16(
    TDataHnd hnd,
    ffi.Pointer<ffi.Uint16> out,
  ) {
    return _LF_ReadUInt16(
      hnd,
      out,
    );
  }

  late final _LF_ReadUInt16Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Uint16>)>>(
      'LF_ReadUInt16');
  late final _LF_ReadUInt16 = _LF_ReadUInt16Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Uint16>)>();

  int LF_ReadInt32(
    TDataHnd hnd,
    ffi.Pointer<ffi.Int32> out,
  ) {
    return _LF_ReadInt32(
      hnd,
      out,
    );
  }

  late final _LF_ReadInt32Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Int32>)>>('LF_ReadInt32');
  late final _LF_ReadInt32 = _LF_ReadInt32Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Int32>)>();

  int LF_ReadUInt32(
    TDataHnd hnd,
    ffi.Pointer<ffi.Uint32> out,
  ) {
    return _LF_ReadUInt32(
      hnd,
      out,
    );
  }

  late final _LF_ReadUInt32Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Uint32>)>>(
      'LF_ReadUInt32');
  late final _LF_ReadUInt32 = _LF_ReadUInt32Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Uint32>)>();

  int LF_ReadInt64(
    TDataHnd hnd,
    ffi.Pointer<ffi.Int64> out,
  ) {
    return _LF_ReadInt64(
      hnd,
      out,
    );
  }

  late final _LF_ReadInt64Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Int64>)>>('LF_ReadInt64');
  late final _LF_ReadInt64 = _LF_ReadInt64Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Int64>)>();

  int LF_ReadUInt64(
    TDataHnd hnd,
    ffi.Pointer<ffi.Uint64> out,
  ) {
    return _LF_ReadUInt64(
      hnd,
      out,
    );
  }

  late final _LF_ReadUInt64Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Uint64>)>>(
      'LF_ReadUInt64');
  late final _LF_ReadUInt64 = _LF_ReadUInt64Ptr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Uint64>)>();

  int LF_ReadSingle(
    TDataHnd hnd,
    ffi.Pointer<ffi.Float> out,
  ) {
    return _LF_ReadSingle(
      hnd,
      out,
    );
  }

  late final _LF_ReadSinglePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Float>)>>('LF_ReadSingle');
  late final _LF_ReadSingle = _LF_ReadSinglePtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Float>)>();

  int LF_ReadDouble(
    TDataHnd hnd,
    ffi.Pointer<ffi.Double> out,
  ) {
    return _LF_ReadDouble(
      hnd,
      out,
    );
  }

  late final _LF_ReadDoublePtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(TDataHnd, ffi.Pointer<ffi.Double>)>>(
      'LF_ReadDouble');
  late final _LF_ReadDouble = _LF_ReadDoublePtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Double>)>();

  /// @brief Reads a null-terminated UTF-8 string from the current position.
  ///
  /// Behavior (matching Pascal's fault-tolerant LF_ReadString in
  /// `lingofuse_import.pas`):
  ///
  /// Case 1 - A #0 is found within the buffer:
  /// The bytes up to (but not including) the #0 are copied into @p buf,
  /// and the cursor is advanced to just past the #0.
  ///
  /// Case 2 - No #0 is found before the end of the buffer (fault-tolerant):
  /// The remaining bytes up to the end of the buffer are copied, and the
  /// cursor is advanced to (buffer size + 1) - i.e. ONE BYTE PAST the
  /// end of the buffer. This matches Pascal's LF_SetPos(Hnd, e + 1)
  /// with e == size: the underlying library implicitly grows the buffer
  /// by one byte to accommodate the new position.
  ///
  /// This case is COMMON when receiving data from an HTTP bridge or a
  /// non-Pascal client that does not append a #0 terminator. The cursor
  /// semantics are identical to the C# / Python / Pascal wrappers.
  ///
  /// Case 3 - No data available (cursor is at or past the end of the buffer):
  /// Returns 0 and sets @p buf to an empty string. The cursor is left
  /// unchanged.
  ///
  /// Case 4 - @p buf is too small to hold the whole string:
  /// Returns 0 and does NOT advance the cursor (caller can retry with a
  /// larger buffer).
  ///
  /// On success, @p buf is always null-terminated.
  ///
  /// This C wrapper does NOT validate UTF-8; the copied bytes are raw.
  ///
  /// @param hnd       Data handle.
  /// @param buf       Output buffer (must be at least 1 byte).
  /// @param buf_size  Size of @p buf in bytes.
  /// @return 1 on success (either Case 1 or Case 2 above), 0 on failure.
  int LF_ReadString(
    TDataHnd hnd,
    ffi.Pointer<ffi.Char> buf,
    int buf_size,
  ) {
    return _LF_ReadString(
      hnd,
      buf,
      buf_size,
    );
  }

  late final _LF_ReadStringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              TDataHnd, ffi.Pointer<ffi.Char>, ffi.Size)>>('LF_ReadString');
  late final _LF_ReadString = _LF_ReadStringPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Char>, int)>();

  /// @brief Reads a byte sequence that is either terminated by a #0 or ends at
  /// the end of the buffer.
  ///
  /// This is the byte-oriented counterpart of LF_ReadString. It mirrors
  /// Pascal's LF_ReadStringBytes:
  ///
  /// Case 1 - A #0 is found:
  /// Copies the bytes up to (but not including) the #0, advances the
  /// cursor past the #0. Returns the number of bytes copied.
  ///
  /// Case 2 - No #0 found before the end of the buffer:
  /// Copies all remaining bytes, advances the cursor to
  /// (buffer size + 1) - i.e. ONE BYTE PAST the end of the buffer.
  /// This matches Pascal's LF_SetPos(Hnd, e + 1) with e == size; the
  /// underlying library implicitly grows the buffer by one byte.
  /// Returns the number of bytes copied.
  ///
  /// Case 3 - No data available (cursor is at or past the end of the buffer):
  /// Returns -1. The cursor is left unchanged.
  ///
  /// Case 4 - @p buf_size is too small:
  /// Returns -1 and does NOT advance the cursor.
  ///
  /// Note: an empty string (just a #0 byte) is a valid input and yields 0
  /// bytes copied with a successful return value of 0.
  ///
  /// @param hnd       Data handle.
  /// @param buf       Destination buffer (may be NULL if @p buf_size is 0).
  /// @param buf_size  Size of @p buf in bytes.
  /// @return Number of bytes copied (>= 0) on success, -1 on failure.
  int LF_ReadStringBytes(
    TDataHnd hnd,
    ffi.Pointer<ffi.Void> buf,
    int buf_size,
  ) {
    return _LF_ReadStringBytes(
      hnd,
      buf,
      buf_size,
    );
  }

  late final _LF_ReadStringBytesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(TDataHnd, ffi.Pointer<ffi.Void>,
              ffi.Int64)>>('LF_ReadStringBytes');
  late final _LF_ReadStringBytes = _LF_ReadStringBytesPtr.asFunction<
      int Function(TDataHnd, ffi.Pointer<ffi.Void>, int)>();
}

/// ----------------------------------------------------------------------------
/// Opaque handle types
/// -------------------------------------------------------------------------
typedef TDataHnd = ffi.Pointer<ffi.Void>;
typedef TAppHnd = ffi.Pointer<ffi.Void>;

/// ----------------------------------------------------------------------------
/// Callback types (all cdecl, all executed on background worker threads)
/// ------------------------------------------------------------------------- */
/// /**
/// @brief Prototype for a Call-mode (request-response) callback.
///
/// @param trigger  User-supplied pointer passed at registration time.
/// @param input    Read-only data handle containing the request payload.
/// @param output   Writable data handle to be filled with the response.
typedef LF_CallFunc = ffi.Pointer<ffi.NativeFunction<LF_CallFuncFunction>>;
typedef LF_CallFuncFunction = ffi.Void Function(ffi.Pointer<ffi.Void> trigger,
    ffi.Pointer<ffi.Void> input, ffi.Pointer<ffi.Void> output);
typedef DartLF_CallFuncFunction = void Function(ffi.Pointer<ffi.Void> trigger,
    ffi.Pointer<ffi.Void> input, ffi.Pointer<ffi.Void> output);

/// @brief Prototype for a Notify-mode (one-way) callback.
///
/// @param trigger  User-supplied pointer passed at registration time.
/// @param input    Read-only data handle containing the notification payload.
typedef LF_NotifyFunc = ffi.Pointer<ffi.NativeFunction<LF_NotifyFuncFunction>>;
typedef LF_NotifyFuncFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> trigger, ffi.Pointer<ffi.Void> input);
typedef DartLF_NotifyFuncFunction = void Function(
    ffi.Pointer<ffi.Void> trigger, ffi.Pointer<ffi.Void> input);

/// @brief Prototype for a network connect/disconnect callback.
///
/// @param addr  UTF-8 endpoint string. Valid ONLY during the callback
/// invocation; copy the string if you need to retain it.
///
/// IMPORTANT: Runs on a background worker thread. Do NOT touch UI directly.
typedef LF_NetworkEventFunc
    = ffi.Pointer<ffi.NativeFunction<LF_NetworkEventFuncFunction>>;
typedef LF_NetworkEventFuncFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> addr);
typedef DartLF_NetworkEventFuncFunction = void Function(
    ffi.Pointer<ffi.Char> addr);
