%% src/lingofuse.erl
%%
%% Public Erlang API for the LingoFuse binding.
%%
%% Every function normalizes the NIF result to {ok, Value} or
%% {error, Reason}, or to ok on success. Argument errors raise badarg.
%%
%% Call callback modes
%% -------------------
%% Two modes are supported:
%%
%%   register_call/4        ASYNC. The registered pid receives
%%                          {lf_call, ApiName, Payload}. The C
%%                          callback returns immediately; the
%%                          LingoFuse output handle is empty. This
%%                          is the original binding behaviour.
%%
%%   register_call_sync/4   SYNC. The registered pid receives
%%                          {lf_call, Ref, ApiName, Payload}. The
%%                          C callback BLOCKS until the pid calls
%%                          reply(Ref, ResultBin) with a binary.
%%                          The payload is written into the
%%                          LingoFuse output handle, so the caller
%%                          of call/3 / local_call/2 sees a normal
%%                          synchronous response.
%%
%%                          If the pid never replies, the C callback
%%                          unblocks after the sync timeout (default
%%                          30000 ms, configurable with
%%                          set_sync_timeout/1) and the output
%%                          handle is left empty.
%%
%%                          A late reply after a timeout returns
%%                          {error, unknown_ref}.
%%
%%   register_notify/4      NOTIFY. The registered pid receives
%%                          {lf_notify, ApiName, Payload}. There is
%%                          no reply path in notify mode.
%%
%% The Ref in a sync message is an opaque non-negative integer
%% generated by the C layer. Callers must pass it back verbatim to
%% reply/2.

-module(lingofuse).

%% NIF availability
-export([ensure_loaded/0]).

%% Data handle
-export([
    create_data/1,
    create_data_permanent/1,
    free_data/1,
    write_buffer/2,
    read_buffer/2,
    get_buffer/1,
    get_pos/1,
    set_pos/2,
    get_size/1,
    set_size/2
]).

%% Application handle
-export([
    create_app/1, create_app/2,
    free_app/1,
    generate_app_name/0,
    get_app_name/1,
    bind_app/1
]).

%% API registration
-export([
    register_call/4,
    register_call_sync/4,
    register_notify/4,
    unregister/2
]).

%% Sync callback bridge
-export([
    reply/2,
    set_sync_timeout/1,
    get_sync_timeout/0
]).

%% Local execution
-export([
    local_call/2,
    local_notify/2
]).

%% Network preparation
-export([
    reset_prepare/0,
    prepare_service/2,
    prepare_client/1, prepare_client/2,
    prepare_done/0,
    exit_main_thread/0
]).

%% Remote invocation
-export([
    call/2, call/3,
    notify/2,
    sequenced_notify/2
]).

%% Options and diagnostics
-export([
    set_option/2,
    post_status/1,
    get_status/0,
    get_status_count/0,
    check_main_thread/0,
    check_app/1,
    check_api/2
]).

%% Shutdown
-export([shutdown/0]).

%% Network events
-export([set_network_event/2]).

%% Types
-type data_handle() :: reference().
-type app_handle()  :: reference().
-type api_name()    :: binary().
-type app_name()    :: binary().
-type endpoint()    :: binary().
-type sync_ref()    :: non_neg_integer().

-export_type([data_handle/0, app_handle/0, sync_ref/0]).

%% =========================================================================
%% NIF availability
%% =========================================================================

-spec ensure_loaded() -> ok | {error, lf_not_loaded}.
ensure_loaded() ->
    try lingofuse_nif:check_main_thread() of
        _ -> ok
    catch
        error:{not_loaded, _} -> {error, lf_not_loaded};
        error:undef           -> {error, lf_not_loaded}
    end.

%% =========================================================================
%% Data handle
%% =========================================================================

-spec create_data(api_name()) -> {ok, data_handle()} | {error, term()}.
create_data(Name) when is_binary(Name) ->
    wrap_handle(lingofuse_nif:create_data(Name));
create_data(_) ->
    error(badarg).

-spec create_data_permanent(api_name()) ->
    {ok, data_handle()} | {error, term()}.
create_data_permanent(Name) when is_binary(Name) ->
    wrap_handle(lingofuse_nif:create_data_permanent(Name));
create_data_permanent(_) ->
    error(badarg).

-spec free_data(data_handle()) -> ok | {error, term()}.
free_data(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:free_data(Hnd));
free_data(_) ->
    error(badarg).

-spec write_buffer(data_handle(), binary()) ->
    {ok, non_neg_integer()} | {error, term()}.
write_buffer(Hnd, Bin) when is_reference(Hnd), is_binary(Bin) ->
    normalize_ok(lingofuse_nif:write_buffer(Hnd, Bin));
write_buffer(_, _) ->
    error(badarg).

-spec read_buffer(data_handle(), non_neg_integer()) ->
    {ok, binary()} | {error, term()}.
read_buffer(Hnd, Count)
        when is_reference(Hnd), is_integer(Count), Count >= 0 ->
    normalize_ok(lingofuse_nif:read_buffer(Hnd, Count));
read_buffer(_, _) ->
    error(badarg).

-spec get_buffer(data_handle()) -> {ok, binary()} | {error, term()}.
get_buffer(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:get_buffer(Hnd));
get_buffer(_) ->
    error(badarg).

-spec get_pos(data_handle()) -> {ok, non_neg_integer()} | {error, term()}.
get_pos(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:get_pos(Hnd));
get_pos(_) ->
    error(badarg).

-spec set_pos(data_handle(), non_neg_integer()) -> ok | {error, term()}.
set_pos(Hnd, Pos) when is_reference(Hnd), is_integer(Pos), Pos >= 0 ->
    normalize_ok(lingofuse_nif:set_pos(Hnd, Pos));
set_pos(_, _) ->
    error(badarg).

-spec get_size(data_handle()) -> {ok, non_neg_integer()} | {error, term()}.
get_size(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:get_size(Hnd));
get_size(_) ->
    error(badarg).

-spec set_size(data_handle(), non_neg_integer()) -> ok | {error, term()}.
set_size(Hnd, Size) when is_reference(Hnd), is_integer(Size), Size >= 0 ->
    normalize_ok(lingofuse_nif:set_size(Hnd, Size));
set_size(_, _) ->
    error(badarg).

%% =========================================================================
%% Application handle
%% =========================================================================

-spec create_app(app_name()) -> {ok, app_handle()} | {error, term()}.
create_app(Name) ->
    create_app(Name, <<>>).

-spec create_app(app_name(), binary()) ->
    {ok, app_handle()} | {error, term()}.
create_app(Name, Desc)
        when is_binary(Name), is_binary(Desc) ->
    wrap_handle(lingofuse_nif:create_app(Name, Desc));
create_app(_, _) ->
    error(badarg).

-spec free_app(app_handle()) -> ok | {error, term()}.
free_app(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:free_app(Hnd));
free_app(_) ->
    error(badarg).

-spec generate_app_name() -> {ok, binary()} | {error, term()}.
generate_app_name() ->
    normalize_ok(lingofuse_nif:generate_app_name()).

-spec get_app_name(app_handle()) -> {ok, binary()} | {error, term()}.
get_app_name(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:get_app_name(Hnd));
get_app_name(_) ->
    error(badarg).

-spec bind_app(app_handle()) -> {ok, non_neg_integer()} | {error, term()}.
bind_app(Hnd) when is_reference(Hnd) ->
    normalize_ok(lingofuse_nif:bind_app(Hnd));
bind_app(_) ->
    error(badarg).

%% =========================================================================
%% API registration
%% =========================================================================

%% Register a Call API in ASYNC mode. The pid receives
%% {lf_call, ApiName, Payload} and the C callback returns
%% immediately. This is the original binding behaviour and is kept
%% unchanged for backward compatibility. Use register_call_sync/4
%% when the caller needs a synchronous output writeback.
-spec register_call(app_handle(), api_name(), binary(), pid()) ->
    ok | {error, term()}.
register_call(App, Name, Desc, Pid)
        when is_reference(App), is_binary(Name), is_binary(Desc),
             is_pid(Pid) ->
    normalize_ok(lingofuse_nif:register_call(App, Name, Desc, Pid));
register_call(_, _, _, _) ->
    error(badarg).

%% Register a Call API in SYNC mode. The pid receives
%% {lf_call, Ref, ApiName, Payload} and MUST call reply/2 with the
%% same Ref and a binary result. The C callback blocks until either
%% the reply arrives or the sync timeout expires.
-spec register_call_sync(app_handle(), api_name(), binary(), pid()) ->
    ok | {error, term()}.
register_call_sync(App, Name, Desc, Pid)
        when is_reference(App), is_binary(Name), is_binary(Desc),
             is_pid(Pid) ->
    normalize_ok(lingofuse_nif:register_call_sync(App, Name, Desc, Pid));
register_call_sync(_, _, _, _) ->
    error(badarg).

%% Register a Notify API. The pid receives {lf_notify, ApiName,
%% Payload} on every incoming notification. There is no reply path.
-spec register_notify(app_handle(), api_name(), binary(), pid()) ->
    ok | {error, term()}.
register_notify(App, Name, Desc, Pid)
        when is_reference(App), is_binary(Name), is_binary(Desc),
             is_pid(Pid) ->
    normalize_ok(lingofuse_nif:register_notify(App, Name, Desc, Pid));
register_notify(_, _, _, _) ->
    error(badarg).

-spec unregister(app_handle(), api_name()) ->
    {ok, boolean()} | {error, term()}.
unregister(App, Name) when is_reference(App), is_binary(Name) ->
    case lingofuse_nif:unregister(App, Name) of
        true  -> {ok, true};
        false -> {ok, false};
        {error, Reason} -> {error, Reason}
    end;
unregister(_, _) ->
    error(badarg).

%% =========================================================================
%% Sync callback bridge
%% =========================================================================

%% Deliver the result of a sync Call callback to the blocked C
%% callback identified by Ref. The payload is written verbatim into
%% the LingoFuse output handle.
%%
%% Returns {error, unknown_ref} when:
%%   - the ref does not correspond to any pending request, or
%%   - the pending request has already timed out on the C side.
%%
%% In both cases the caller may safely ignore the error.
-spec reply(sync_ref(), binary()) -> ok | {error, term()}.
reply(Ref, ResultBin)
        when is_integer(Ref), Ref >= 0, is_binary(ResultBin) ->
    normalize_ok(lingofuse_nif:reply(Ref, ResultBin));
reply(_, _) ->
    error(badarg).

%% Change the process-wide sync callback timeout, in milliseconds.
%% Values below 100 ms are clamped to 100 ms by the C side. The
%% default is 30000 ms.
-spec set_sync_timeout(pos_integer()) -> ok | {error, term()}.
set_sync_timeout(Ms) when is_integer(Ms), Ms > 0 ->
    normalize_ok(lingofuse_nif:set_sync_timeout(Ms));
set_sync_timeout(_) ->
    error(badarg).

%% Return the current sync callback timeout, in milliseconds.
-spec get_sync_timeout() -> {ok, pos_integer()} | {error, term()}.
get_sync_timeout() ->
    normalize_ok(lingofuse_nif:get_sync_timeout()).

%% =========================================================================
%% Local execution
%% =========================================================================

-spec local_call(app_handle(), data_handle()) ->
    {ok, data_handle()} | {error, term()}.
local_call(App, Param) when is_reference(App), is_reference(Param) ->
    wrap_handle(lingofuse_nif:local_call(App, Param));
local_call(_, _) ->
    error(badarg).

-spec local_notify(app_handle(), data_handle()) -> ok | {error, term()}.
local_notify(App, Param) when is_reference(App), is_reference(Param) ->
    normalize_ok(lingofuse_nif:local_notify(App, Param));
local_notify(_, _) ->
    error(badarg).

%% =========================================================================
%% Network preparation
%% =========================================================================

-spec reset_prepare() -> ok | {error, term()}.
reset_prepare() ->
    normalize_ok(lingofuse_nif:reset_prepare()).

-spec prepare_service(endpoint(), endpoint()) ->
    {ok, integer()} | {error, term()}.
prepare_service(Listen, Physics)
        when is_binary(Listen), is_binary(Physics) ->
    normalize_ok(lingofuse_nif:prepare_service(Listen, Physics));
prepare_service(_, _) ->
    error(badarg).

-spec prepare_client(endpoint()) -> {ok, integer()} | {error, term()}.
prepare_client(Addr) ->
    prepare_client(Addr, undefined).

-spec prepare_client(endpoint(), app_handle() | undefined) ->
    {ok, integer()} | {error, term()}.
prepare_client(Addr, App)
        when is_binary(Addr), is_reference(App) ->
    normalize_ok(lingofuse_nif:prepare_client(Addr, App));
prepare_client(Addr, undefined) when is_binary(Addr) ->
    normalize_ok(lingofuse_nif:prepare_client(Addr, undefined));
prepare_client(_, _) ->
    error(badarg).

-spec prepare_done() -> {ok, integer()} | {error, term()}.
prepare_done() ->
    normalize_ok(lingofuse_nif:prepare_done()).

-spec exit_main_thread() -> ok | {error, term()}.
exit_main_thread() ->
    normalize_ok(lingofuse_nif:exit_main_thread()).

%% =========================================================================
%% Remote invocation
%% =========================================================================

-spec call(app_name(), data_handle()) ->
    {ok, data_handle()} | {error, term()}.
call(App, Param) ->
    call(App, Param, 5000).

-spec call(app_name(), data_handle(), non_neg_integer()) ->
    {ok, data_handle()} | {error, term()}.
call(App, Param, Timeout)
        when is_binary(App), is_reference(Param),
             is_integer(Timeout), Timeout >= 0 ->
    wrap_handle(lingofuse_nif:call(App, Param, Timeout));
call(_, _, _) ->
    error(badarg).

-spec notify(app_name(), data_handle()) -> ok | {error, term()}.
notify(App, Param) when is_binary(App), is_reference(Param) ->
    normalize_ok(lingofuse_nif:notify(App, Param));
notify(_, _) ->
    error(badarg).

-spec sequenced_notify(app_name(), data_handle()) -> ok | {error, term()}.
sequenced_notify(App, Param) when is_binary(App), is_reference(Param) ->
    normalize_ok(lingofuse_nif:sequenced_notify(App, Param));
sequenced_notify(_, _) ->
    error(badarg).

%% =========================================================================
%% Options and diagnostics
%% =========================================================================

-spec set_option(binary(), binary()) -> ok | {error, term()}.
set_option(Opt, Val) when is_binary(Opt), is_binary(Val) ->
    normalize_ok(lingofuse_nif:set_option(Opt, Val));
set_option(_, _) ->
    error(badarg).

-spec post_status(binary()) -> ok | {error, term()}.
post_status(Status) when is_binary(Status) ->
    normalize_ok(lingofuse_nif:post_status(Status));
post_status(_) ->
    error(badarg).

-spec get_status() -> {ok, binary()} | {error, term()}.
get_status() ->
    normalize_ok(lingofuse_nif:get_status()).

-spec get_status_count() -> {ok, integer()} | {error, term()}.
get_status_count() ->
    normalize_ok(lingofuse_nif:get_status_count()).

-spec check_main_thread() -> {ok, boolean()} | {error, term()}.
check_main_thread() ->
    normalize_ok(lingofuse_nif:check_main_thread()).

-spec check_app(app_name()) -> {ok, boolean()} | {error, term()}.
check_app(App) when is_binary(App) ->
    normalize_ok(lingofuse_nif:check_app(App));
check_app(_) ->
    error(badarg).

-spec check_api(app_name(), api_name()) -> {ok, boolean()} | {error, term()}.
check_api(App, Api) when is_binary(App), is_binary(Api) ->
    normalize_ok(lingofuse_nif:check_api(App, Api));
check_api(_, _) ->
    error(badarg).

%% =========================================================================
%% Shutdown
%% =========================================================================

-spec shutdown() -> ok | {error, term()}.
shutdown() ->
    normalize_ok(lingofuse_nif:shutdown()).

%% =========================================================================
%% Network events
%% =========================================================================

-spec set_network_event(pid() | undefined, pid() | undefined) ->
    ok | {error, term()}.
set_network_event(Connect, Disconnect)
        when is_pid(Connect), is_pid(Disconnect) ->
    normalize_ok(lingofuse_nif:set_network_event(Connect, Disconnect));
set_network_event(Connect, undefined) when is_pid(Connect) ->
    normalize_ok(lingofuse_nif:set_network_event(Connect, undefined));
set_network_event(undefined, Disconnect) when is_pid(Disconnect) ->
    normalize_ok(lingofuse_nif:set_network_event(undefined, Disconnect));
set_network_event(undefined, undefined) ->
    normalize_ok(lingofuse_nif:set_network_event(undefined, undefined));
set_network_event(_, _) ->
    error(badarg).

%% =========================================================================
%% Internal helpers
%% =========================================================================

wrap_handle(Value) ->
    try
        case Value of
            {error, _} = Err -> Err;
            Term when is_reference(Term) -> {ok, Term};
            Term -> {ok, Term}
        end
    catch
        error:{not_loaded, _} -> {error, lf_not_loaded}
    end.

normalize_ok(Value) ->
    try
        case Value of
            ok              -> ok;
            {error, _} = E  -> E;
            Term            -> {ok, Term}
        end
    catch
        error:{not_loaded, _} -> {error, lf_not_loaded}
    end.