<#
.SYNOPSIS
    Build and install the lingofuse R package.

.DESCRIPTION
    1. Copies the current bridge source files from c_ext\src\ into the
       package's src\ directory.
    2. If NAMESPACE or man\ is missing, generates them with roxygen2.
    3. Runs R CMD INSTALL on the lingofuse package.
    4. Runs a post-install verification script with Rscript.exe.

    The source files are copied (not symlinked) because R CMD INSTALL
    expects a self-contained src\ directory. The c_ext\src\ tree
    remains the single source of truth; this script is the only place
    that copies it.

    Re-run this script after every change to c_ext\src\*.{c,h,cpp,hpp}.

.PARAMETER Rebuild
    Delete the package's src\*.o / *.dll / *.so artifacts before
    building, forcing a full recompile.

.PARAMETER NoRoxygen
    Skip the automatic roxygen2 regeneration step.
#>

[CmdletBinding()]
param(
    [switch]$Rebuild,
    [switch]$NoRoxygen
)

$ErrorActionPreference = "Stop"

$Root        = $PSScriptRoot
$SourceDir   = Join-Path $Root "c_ext\src"
$PkgDir      = Join-Path $Root "lingofuse"
$PkgSrcDir   = Join-Path $PkgDir "src"
$PkgManDir   = Join-Path $PkgDir "man"
$PkgNsPath   = Join-Path $PkgDir "NAMESPACE"

$SourceFiles = @(
    "lf_r_shim.c",
    "lf_r_shim.h",
    "lf_bridge.cpp",
    "lf_loader.h"
)

function Write-Section { param([string]$T)
    Write-Host ""
    Write-Host ("=" * 72) -ForegroundColor Cyan
    Write-Host $T -ForegroundColor Cyan
    Write-Host ("=" * 72) -ForegroundColor Cyan
}
function Write-Ok   { param([string]$T) Write-Host ("[OK]   " + $T) -ForegroundColor Green }
function Write-Info { param([string]$T) Write-Host ("       " + $T) -ForegroundColor Gray }
function Write-Warn { param([string]$T) Write-Host ("[WARN] " + $T) -ForegroundColor Yellow }
function Write-Fail { param([string]$T) Write-Host ("[FAIL] " + $T) -ForegroundColor Red }

Write-Section "lingofuse R package - build"

# ---- Pre-flight --------------------------------------------------------------
$rExe = Get-Command R.exe -ErrorAction SilentlyContinue
if (-not $rExe) {
    Write-Fail "R.exe not found on PATH."
    exit 1
}
Write-Ok ("R.exe: " + $rExe.Source)

$rscriptExe = Get-Command Rscript.exe -ErrorAction SilentlyContinue
if (-not $rscriptExe) {
    Write-Fail "Rscript.exe not found on PATH."
    exit 1
}
Write-Ok ("Rscript.exe: " + $rscriptExe.Source)

if (-not (Test-Path $PkgDir)) {
    Write-Fail ("Package directory not found: " + $PkgDir)
    Write-Info "Create it and populate DESCRIPTION, R\, etc."
    exit 1
}

# DESCRIPTION, R\, and src\Makevars[.win] are hand-maintained. NAMESPACE
# and man\ are generated by roxygen2 and are therefore NOT required to
# exist before the first build.
foreach ($f in @("DESCRIPTION", "R\api.R", "R\zzz.R")) {
    $p = Join-Path $PkgDir $f
    if (-not (Test-Path $p)) {
        Write-Fail ("Missing package file: " + $f)
        exit 1
    }
}
Write-Ok "Package skeleton is present"

# ---- Copy sources ------------------------------------------------------------
Write-Section "Copying bridge sources into lingofuse\src\"

if (-not (Test-Path $PkgSrcDir)) {
    New-Item -ItemType Directory -Path $PkgSrcDir -Force | Out-Null
    Write-Info ("Created: " + $PkgSrcDir)
}

if ($Rebuild) {
    Get-ChildItem -Path $PkgSrcDir -Include "*.o","*.obj","*.so","*.dll" `
        -File -ErrorAction SilentlyContinue |
        ForEach-Object { Remove-Item -Force $_.FullName; Write-Info ("removed " + $_.Name) }
}

foreach ($f in $SourceFiles) {
    $src = Join-Path $SourceDir $f
    if (-not (Test-Path $src)) {
        Write-Fail ("Missing source: " + $src)
        exit 1
    }
    Copy-Item -Force $src (Join-Path $PkgSrcDir $f)
    Write-Ok ("copied " + $f)
}

# Makevars / Makevars.win are part of the package, not copied from c_ext.
foreach ($mk in @("Makevars", "Makevars.win")) {
    $p = Join-Path $PkgSrcDir $mk
    if (-not (Test-Path $p)) {
        Write-Fail ("Missing package file: src\" + $mk)
        exit 1
    }
}

# ---- Roxygen2 regeneration (only when NAMESPACE or man\ is missing) ----------
$manEmpty = $true
if (Test-Path $PkgManDir) {
    $manFiles = @(Get-ChildItem -Path $PkgManDir -Filter "*.Rd" -File -ErrorAction SilentlyContinue)
    if ($manFiles.Count -gt 0) { $manEmpty = $false }
}

if ($NoRoxygen) {
    Write-Info "Roxygen2 regeneration skipped (-NoRoxygen)."
} elseif (-not (Test-Path $PkgNsPath) -or $manEmpty) {
    Write-Section "Regenerating roxygen2 output"

    # Roxygen2 (via pkgload::load_all) requires NAMESPACE to exist
    # before it can load the package. Write a minimal stub first; the
    # subsequent roxygenise() call will overwrite it with the full
    # generated file.
    if (-not (Test-Path $PkgNsPath)) {
        Write-Info "Writing a minimal NAMESPACE stub for roxygen2..."
        @'
# Generated by roxygen2: do not edit by hand

useDynLib(lingofuse, .registration = TRUE, .fixes = "C_")
'@ | Set-Content -Path $PkgNsPath -Encoding ASCII
    }

    Push-Location $Root
    try {
        & $rscriptExe.Source "-e" "roxygen2::roxygenise('lingofuse')"
        $roxRc = $LASTEXITCODE
    } finally {
        Pop-Location
    }

    if ($roxRc -ne 0) {
        Write-Warn "roxygenise failed."
        Write-Warn "Install roxygen2 with:"
        Write-Warn "    Rscript -e `"install.packages('roxygen2')`""
        Write-Warn "Continuing without regenerated documentation."
    } else {
        Write-Ok "roxygen2 output regenerated."
    }
} else {
    $rdCount = @(Get-ChildItem -Path $PkgManDir -Filter "*.Rd" -File).Count
    Write-Info ("Roxygen2 output present (NAMESPACE + " + $rdCount + " .Rd file(s)).")
}

# ---- R CMD INSTALL -----------------------------------------------------------
Write-Section "Running R CMD INSTALL"

Push-Location $Root
try {
    & $rExe.Source CMD INSTALL --preclean $PkgDir
    $rc = $LASTEXITCODE
} finally {
    Pop-Location
}

if ($rc -ne 0) {
    Write-Fail ("R CMD INSTALL failed (exit code " + $rc + ").")
    exit $rc
}

Write-Ok "lingofuse installed"

# ---- Verification ------------------------------------------------------------
Write-Section "Verifying the installed package"

$verifyScript = @'
ok <- TRUE
tryCatch({
    suppressPackageStartupMessages(library(lingofuse))
    cat("  package loaded:", isNamespaceLoaded("lingofuse"), "\n")
    cat("  lf_load is a function:", is.function(lingofuse::lf_load), "\n")
    cat("  lf_call is a function:", is.function(lingofuse::lf_call), "\n")
    cat("  lf_find_runtime       :", is.function(lingofuse::lf_find_runtime), "\n")

    lib_dir <- system.file("libs", package = "lingofuse")
    cat("  package libs dir:", lib_dir, "\n")
}, error = function(e) {
    cat("  ERROR:", conditionMessage(e), "\n")
    ok <<- FALSE
})
if (!ok) quit(status = 1)
'@

$tmp = Join-Path $env:TEMP ("lingofuse_verify_" + [Guid]::NewGuid().ToString("N").Substring(0,8) + ".R")
Set-Content -Path $tmp -Value $verifyScript -Encoding ASCII

& $rscriptExe.Source "--vanilla" $tmp
$verifyRc = $LASTEXITCODE
Remove-Item -Force $tmp -ErrorAction SilentlyContinue

if ($verifyRc -ne 0) {
    Write-Fail "Post-install verification failed."
    exit 1
}
Write-Ok "Package loads and exports the expected functions"

Write-Section "Build Summary"
Write-Host "  Package : lingofuse"
Write-Host "  Source  : " + $PkgSrcDir
Write-Host ""
Write-Host "Try it (no hard-coded path):" -ForegroundColor White
Write-Host "  `$env:LINGOFUSE_RUNTIME = '<runtime_dir>'" -ForegroundColor Gray
Write-Host "  Rscript -e `"library(lingofuse); lf_is_loaded()`"" -ForegroundColor Gray
Write-Host ""

exit 0