<#
.SYNOPSIS
    Remove build artifacts of the LingoFuse R bridge and R package.

.DESCRIPTION
    Level 1 (default): removes only artifacts that are regenerated by
    running build.ps1 / build_package.ps1 again.

        - c_ext\src\*.o, *.obj, *.dll, *.so, *.dylib
        - c_ext\tests\*.o, *.obj, *.exe, *.dll, *.so, *.rout
        - c_ext\*.o, *.obj, *.exe, *.dll, *.so, *.rout
        - libs\ (contents only; the directory itself is preserved)
        - lingofuse\src\*.o, *.obj, *.dll, *.so, *.dylib
        - _check_*\ (R CMD check artifact directories at the repo root)
        - r\*.Rout (R BATCH output)

    Level 2 (-All): additionally removes every generated file, so that
    the next build starts from a clean source tree.

        - libs\ itself
        - lingofuse\man\ (roxygen2-generated .Rd files)
        - lingofuse\NAMESPACE (roxygen2-generated)
        - lingofuse\src\{lf_r_shim.c, lf_r_shim.h, lf_bridge.cpp,
          lf_loader.h} (copied from c_ext\src\ by build_package.ps1)

    Files that are NEVER touched:

        - All *.c, *.cpp, *.h, *.hpp under c_ext\
        - All *.R under c_ext\tests\ and demo\
        - All *.ps1
        - .vscode\
        - lingofuse\DESCRIPTION, LICENSE, R\, inst\, tests\
        - lingofuse\src\Makevars, Makevars.win (hand-maintained)

.PARAMETER All
    Also remove roxygen2-generated files and the copied source files
    inside lingofuse\src\. Use this when you want a completely clean
    tree; the next build.ps1 / build_package.ps1 regenerates everything.

.PARAMETER Quiet
    Suppress per-item removal messages.
#>

[CmdletBinding()]
param(
    [switch]$All,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

$Root        = $PSScriptRoot
$SourceDir   = Join-Path $Root "c_ext\src"
$TestsDir    = Join-Path $Root "c_ext\tests"
$CExtDir     = Join-Path $Root "c_ext"
$LibsDir     = Join-Path $Root "libs"
$PkgDir      = Join-Path $Root "lingofuse"
$PkgSrcDir   = Join-Path $PkgDir "src"
$PkgManDir   = Join-Path $PkgDir "man"

# The four source files that build_package.ps1 copies from c_ext\src\
# into lingofuse\src\. Removing them from the package is safe only when
# -All is set, because the next build_package.ps1 run recreates them.
$CopiedSourceNames = @(
    "lf_r_shim.c",
    "lf_r_shim.h",
    "lf_bridge.cpp",
    "lf_loader.h"
)

function Write-Section {
    param([string]$Text)
    Write-Host ""
    Write-Host ("=" * 72) -ForegroundColor Cyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 72) -ForegroundColor Cyan
}

function Write-Removed {
    param([string]$Text)
    if (-not $Quiet) { Write-Host ("[DEL]  " + $Text) -ForegroundColor Yellow }
}

function Write-Kept {
    param([string]$Text)
    if (-not $Quiet) { Write-Host ("[KEEP] " + $Text) -ForegroundColor Gray }
}

function Write-Ok {
    param([string]$Text)
    Write-Host ("[OK]   " + $Text) -ForegroundColor Green
}

function Remove-FilesByExtension {
    param([string]$Directory, [string[]]$Extensions)
    if (-not (Test-Path $Directory)) { return 0 }
    $found = @(Get-ChildItem -Path $Directory -File -ErrorAction SilentlyContinue |
               Where-Object { $Extensions -contains $_.Extension.ToLower() })
    foreach ($f in $found) {
        Remove-Item -Force $f.FullName
        Write-Removed $f.FullName
    }
    return $found.Count
}

Write-Section "LingoFuse R - Clean"

$RemovedCount = 0

# --- 1. c_ext\src\ ------------------------------------------------------------
$n = Remove-FilesByExtension -Directory $SourceDir `
    -Extensions @(".o", ".obj", ".dll", ".so", ".dylib")
$RemovedCount += $n
if ($n -eq 0) { Write-Kept "c_ext\src (nothing to remove)" }

# --- 2. c_ext\tests\ ----------------------------------------------------------
$n = Remove-FilesByExtension -Directory $TestsDir `
    -Extensions @(".o", ".obj", ".exe", ".dll", ".so", ".dylib", ".rout")
$RemovedCount += $n
if ($n -eq 0) { Write-Kept "c_ext\tests (nothing to remove)" }

# --- 3. c_ext\ top level ------------------------------------------------------
$n = Remove-FilesByExtension -Directory $CExtDir `
    -Extensions @(".o", ".obj", ".exe", ".dll", ".so", ".dylib", ".rout")
$RemovedCount += $n

# --- 4. r\ top level Rout -----------------------------------------------------
$n = Remove-FilesByExtension -Directory $Root -Extensions @(".rout")
$RemovedCount += $n

# --- 5. lingofuse\src\ object files and shared libraries ---------------------
$n = Remove-FilesByExtension -Directory $PkgSrcDir `
    -Extensions @(".o", ".obj", ".dll", ".so", ".dylib")
$RemovedCount += $n
if ($n -eq 0) { Write-Kept "lingofuse\src (no build artifacts)" }

# --- 6. libs\ -----------------------------------------------------------------
if (Test-Path $LibsDir) {
    if ($All) {
        Remove-Item -Recurse -Force $LibsDir
        Write-Removed $LibsDir
        $RemovedCount++
    } else {
        $items = @(Get-ChildItem -Path $LibsDir -Force -ErrorAction SilentlyContinue)
        foreach ($item in $items) {
            Remove-Item -Recurse -Force $item.FullName
            Write-Removed $item.FullName
            $RemovedCount++
        }
        if ($items.Count -eq 0) {
            Write-Kept "libs (already empty)"
        } else {
            Write-Kept "libs (directory preserved)"
        }
    }
} else {
    Write-Kept "libs (not present)"
}

# --- 7. _check_*\ directories -------------------------------------------------
$checkDirs = @(Get-ChildItem -Path $Root -Directory -ErrorAction SilentlyContinue |
               Where-Object { $_.Name -like "_check_*" })
foreach ($d in $checkDirs) {
    Remove-Item -Recurse -Force $d.FullName
    Write-Removed $d.FullName
    $RemovedCount++
}
if ($checkDirs.Count -eq 0) { Write-Kept "_check_* (none)" }

# --- 8. -All only: roxygen2 output and copied sources ------------------------
if ($All) {
    Write-Section "-All: removing roxygen2 output and copied sources"

    # 8a. man\ (roxygen2-generated)
    if (Test-Path $PkgManDir) {
        $manFiles = @(Get-ChildItem -Path $PkgManDir -File -ErrorAction SilentlyContinue)
        foreach ($f in $manFiles) {
            Remove-Item -Force $f.FullName
            Write-Removed $f.FullName
            $RemovedCount++
        }
        if ($manFiles.Count -gt 0) {
            # If the directory is now empty, remove it too.
            if (@(Get-ChildItem -Path $PkgManDir -Force -ErrorAction SilentlyContinue).Count -eq 0) {
                Remove-Item -Force $PkgManDir
                Write-Removed $PkgManDir
            }
        }
    }

    # 8b. NAMESPACE (roxygen2-generated)
    $ns = Join-Path $PkgDir "NAMESPACE"
    if (Test-Path $ns) {
        # Confirm the file is roxygen2-generated before removing it.
        $first = (Get-Content $ns -TotalCount 1) -join ""
        if ($first -match "Generated by roxygen2") {
            Remove-Item -Force $ns
            Write-Removed $ns
            $RemovedCount++
        } else {
            Write-Kept "$ns (not roxygen2-generated; preserved)"
        }
    }

    # 8c. Copied sources inside lingofuse\src\ (recreated by build_package.ps1)
    foreach ($name in $CopiedSourceNames) {
        $p = Join-Path $PkgSrcDir $name
        if (Test-Path $p) {
            Remove-Item -Force $p
            Write-Removed $p
            $RemovedCount++
        }
    }

    # 8d. Note: Makevars and Makevars.win are hand-maintained.
    foreach ($name in @("Makevars", "Makevars.win")) {
        $p = Join-Path $PkgSrcDir $name
        if (Test-Path $p) { Write-Kept $p }
    }
}

# --- Summary ------------------------------------------------------------------
Write-Section "Clean Summary"
Write-Host ("  Removed items : " + $RemovedCount)
Write-Host ""

if ($RemovedCount -eq 0) {
    Write-Ok "Nothing to clean. The tree was already clean."
} else {
    Write-Ok "Clean complete."
    Write-Host ""
    Write-Host "  To rebuild from scratch:" -ForegroundColor White
    Write-Host "      .\build.ps1 -Rebuild" -ForegroundColor Gray
    Write-Host "      .\build_package.ps1 -Rebuild" -ForegroundColor Gray
    Write-Host ""
}

exit 0