# =============================================================================
# server.R
# -----------------------------------------------------------------------------
# Minimal LingoFuse R service. Run this in one terminal, then run
# client.R in another.
#
# Usage:
#   Rscript demo/server.R [runtime_dir] [wait_sec]
#
# Runtime directory resolution (self-contained; no external file, no
# hard-coded absolute path):
#   1. First command-line argument.
#   2. LINGOFUSE_RUNTIME environment variable.
#   3. "lingofuse.runtime" R option.
#   4. Relative probes under the script directory and the CWD:
#        <script_dir>/Binary, ../Binary, ../../Binary, ...
#      A checkout that places the runtime in <repo>/Binary/ will be
#      found automatically from any launch directory.
#
# The resolver is inlined into this script so that the demo is fully
# self-contained: it does not require the lingofuse package to export
# any runtime-location helper, and it works before NAMESPACE has been
# regenerated by roxygen2.
# =============================================================================

# -----------------------------------------------------------------------------
# Self-contained runtime directory resolver
# -----------------------------------------------------------------------------
lf_resolve_runtime_dir <- function(explicit = NULL, script_dir = NULL) {
    check_dir <- function(path) {
        if (is.null(path) || !is.character(path) || length(path) != 1L ||
            !nzchar(path)) {
            return(NULL)
        }
        if (dir.exists(path)) {
            return(normalizePath(path, winslash = "/", mustWork = FALSE))
        }
        NULL
    }

    if (!is.null(explicit) && nzchar(explicit)) {
        return(check_dir(explicit))
    }

    env_val <- Sys.getenv("LINGOFUSE_RUNTIME", unset = "")
    if (nzchar(env_val)) {
        r <- check_dir(env_val)
        if (!is.null(r)) return(r)
    }

    opt_val <- getOption("lingofuse.runtime", default = "")
    if (is.character(opt_val) && length(opt_val) == 1L && nzchar(opt_val)) {
        r <- check_dir(opt_val)
        if (!is.null(r)) return(r)
    }

    bases <- character(0)
    if (!is.null(script_dir) && nzchar(script_dir)) {
        bases <- c(bases, script_dir)
    }
    bases <- c(bases, getwd())

    relatives <- c(
        "Binary",
        "runtime",
        "runtime/Binary",
        "lib",
        "../Binary",
        "../runtime",
        "../runtime/Binary",
        "../../Binary",
        "../../runtime",
        "../../runtime/Binary",
        "../../../Binary"
    )

    for (base in bases) {
        for (rel in relatives) {
            r <- check_dir(file.path(base, rel))
            if (!is.null(r)) return(r)
        }
    }

    NULL
}

# -----------------------------------------------------------------------------
# Locate the calling script's directory
# -----------------------------------------------------------------------------
script_dir <- tryCatch({
    file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE),
                     value = TRUE)
    if (length(file_arg) > 0) {
        dirname(normalizePath(sub("^--file=", "", file_arg[1])))
    } else {
        getwd()
    }
}, error = function(e) getwd())

# -----------------------------------------------------------------------------
# Parse command-line arguments
# -----------------------------------------------------------------------------
cli_args <- commandArgs(trailingOnly = TRUE)

explicit_runtime <- if (length(cli_args) >= 1) cli_args[1] else NULL
runtime_dir <- lf_resolve_runtime_dir(explicit_runtime, script_dir)
if (is.null(runtime_dir)) {
    message("[FAIL] Could not locate the LingoFuse runtime directory.")
    message("       Provide it as the first argument, set the")
    message("       LINGOFUSE_RUNTIME environment variable, or place it")
    message("       in Binary/ relative to this repository.")
    quit(status = 1)
}

wait_sec <- if (length(cli_args) >= 2) {
    parsed <- suppressWarnings(as.integer(cli_args[2]))
    if (is.na(parsed) || parsed <= 0L) {
        message("[FAIL] wait_sec must be a positive integer, got: ",
                cli_args[2])
        quit(status = 1)
    }
    parsed
} else {
    60L
}

Sys.setenv(LINGOFUSE_RUNTIME = runtime_dir)
message("[OK]   Runtime dir: ", runtime_dir)
message("[OK]   Wait timeout: ", wait_sec, " s")

# -----------------------------------------------------------------------------
# Load the package. The runtime was already located above; the package
# picks it up through the LINGOFUSE_RUNTIME environment variable set by
# this script.
# -----------------------------------------------------------------------------
suppressPackageStartupMessages(library(lingofuse))
suppressPackageStartupMessages(library(jsonlite))

# -----------------------------------------------------------------------------
# Service definition
# -----------------------------------------------------------------------------
app <- lf_create_app("CalcR", "R calculator demo")

lf_register_call(app, "add", "add two integers", function(input) {
    req <- fromJSON(input)
    toJSON(list(result = req$a + req$b), auto_unbox = TRUE)
})

lf_prepare_service("ipc:r_calc", "ipc:r_calc")
lf_prepare_client("ipc:r_calc", app)
stopifnot(lf_prepare_done() == 1L)

cat("[server] online: CalcR @ ipc:r_calc\n")
cat("[server] pumping for up to ", wait_sec, " seconds. Ctrl+C to stop.\n")

tryCatch({
    start <- Sys.time()
    while (as.numeric(Sys.time() - start, units = "secs") < wait_sec) {
        lf_poll(100)
    }
}, interrupt = function(e) NULL)

cat("[server] shutting down\n")
lf_cleanup(app)